//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_CURD_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paitent_info
    {
        public int paitent_id { get; set; }
        public string paitent_name { get; set; }
        public int paitent_age { get; set; }
        public System.DateTime paitent_visitdate { get; set; }
        public string paitent_symptoms { get; set; }
        public string paitent_medications { get; set; }
    }
}
