//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_CURD_Demo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebAPIDemo_DBEntities : DbContext,IPaitentContext
    {
        public WebAPIDemo_DBEntities()
            : base("name=WebAPIDemo_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public void MarkAsModified(Paitent_info item)
        {
            Entry(item).State = EntityState.Modified;
        }
        public DbSet<Paitent_info> Paitents { get; set; }
        // public virtual DbSet<Paitent_info> Paitent_info { get; set; }
    }
}
